2020-11-24 18:32:35 :: ERROR :: FileName : new.py, LineNumber : 734, ExceptionType : <class 'TypeError'>, Exception : write() takes exactly one argument (2 given)

